#! /bin/bash

#
# This tool is released AS-IS. You are free to copy, modify, or shred it.
# 
# Author: Yu Feng <rainwoodman@gmail.com> 2016
# 

function usage {
    echo "ar-join target.a source.a [ additional library archives .... ]"
    echo
    echo "Join multiple library archives into one."
    echo "This script works around the lack of -M option on Mac systems."
    echo "It depends on a posix 'ar' command."
    exit 0
}

if [ x"$1" == "x-h" ]; then
    usage
fi

if [ "x$AR" == x ]; then
    AR=ar
fi

function push {
    local DEST
    local BASENAME
    if ! [ -f $2 ]; then
        echo Archive file $2 not found.
        exit 1
    fi
    echo Adding $2 to $1 ...
    (
        DEST=`mktemp -d XXXXXX`
        trap "rm -rf $DEST" EXIT
        BASENAME=`basename $2`
        cp $2 $DEST || exit 1
        (cd $DEST; "$AR" x $BASENAME; for i in *.o; do mv $i $BASENAME-$i; done ) || exit 1
        "$AR" rc $1 $DEST/*.o || exit 1
    )
}

OUTPUT=$1
shift
for i in $*; do
    push "$OUTPUT" "$i" || exit 1
done
echo Done.

