DEPCMD ?= gcc -MG -MT .objs/$(<:%.c=%.o) -MM 

.objs/%.o : %.c
	@if ! [ -d .objs ]; then mkdir .objs; fi
	@echo Compiling $@
	@$(CC) $(OPTIMIZE) $(OPENMP) -c $(CPPFLAGS) -o $@ $<

.deps/%.d : %.c
	@if ! [ -d .deps ]; then mkdir .deps; fi
	@if ! $(DEPCMD) $(CPPFLAGS) -o $@ $< ; then \
		rm $@; \
	fi;
