        typedef struct LuaConfig LuaConfig;

        void lua_config_free(LuaConfig * lc);
        LuaConfig * lua_config_new(const char * luastring);
        const char * lua_config_error(LuaConfig * lc);
        /* call global lua function with filename and arg as arguments */
        char * lua_config_parse(char * entrypoint, char * filename, int argc, char ** argv, char ** error);
            int lua_config_has_nc(LuaConfig * lc);
            int lua_config_get_nc(LuaConfig * lc);
            int lua_config_has_boxsize(LuaConfig * lc);
            double lua_config_get_boxsize(LuaConfig * lc);
            int lua_config_has_time_step(LuaConfig * lc);
            double * lua_config_get_time_step_full(LuaConfig * lc, int * size);
            double * lua_config_get_time_step(LuaConfig * lc);
            int lua_config_get_n_time_step(LuaConfig * lc);
            int lua_config_get_ndim_time_step(LuaConfig * lc);
            int * lua_config_get_shape_time_step(LuaConfig * lc);
            int lua_config_has_output_redshifts(LuaConfig * lc);
            double * lua_config_get_output_redshifts_full(LuaConfig * lc, int * size);
            double * lua_config_get_output_redshifts(LuaConfig * lc);
            int lua_config_get_n_output_redshifts(LuaConfig * lc);
            int lua_config_get_ndim_output_redshifts(LuaConfig * lc);
            int * lua_config_get_shape_output_redshifts(LuaConfig * lc);
            int lua_config_has_aout(LuaConfig * lc);
            double * lua_config_get_aout_full(LuaConfig * lc, int * size);
            double * lua_config_get_aout(LuaConfig * lc);
            int lua_config_get_n_aout(LuaConfig * lc);
            int lua_config_get_ndim_aout(LuaConfig * lc);
            int * lua_config_get_shape_aout(LuaConfig * lc);
            int lua_config_has_omega_m(LuaConfig * lc);
            double lua_config_get_omega_m(LuaConfig * lc);
            int lua_config_has_Omega_m(LuaConfig * lc);
            double lua_config_get_Omega_m(LuaConfig * lc);
            int lua_config_has_T_cmb(LuaConfig * lc);
            double lua_config_get_T_cmb(LuaConfig * lc);
            int lua_config_has_h(LuaConfig * lc);
            double lua_config_get_h(LuaConfig * lc);
            int lua_config_has_Omega_k(LuaConfig * lc);
            double lua_config_get_Omega_k(LuaConfig * lc);
            int lua_config_has_w0(LuaConfig * lc);
            double lua_config_get_w0(LuaConfig * lc);
            int lua_config_has_wa(LuaConfig * lc);
            double lua_config_get_wa(LuaConfig * lc);
            int lua_config_has_N_eff(LuaConfig * lc);
            double lua_config_get_N_eff(LuaConfig * lc);
            int lua_config_has_N_nu(LuaConfig * lc);
            double lua_config_get_N_nu(LuaConfig * lc);
            int lua_config_has_m_ncdm(LuaConfig * lc);
            double * lua_config_get_m_ncdm_full(LuaConfig * lc, int * size);
            double * lua_config_get_m_ncdm(LuaConfig * lc);
            int lua_config_get_n_m_ncdm(LuaConfig * lc);
            int lua_config_get_ndim_m_ncdm(LuaConfig * lc);
            int * lua_config_get_shape_m_ncdm(LuaConfig * lc);
            int lua_config_has_pm_nc_factor(LuaConfig * lc);
            double * lua_config_get_pm_nc_factor_full(LuaConfig * lc, int * size);
            double * lua_config_get_pm_nc_factor(LuaConfig * lc);
            int lua_config_get_n_pm_nc_factor(LuaConfig * lc);
            int lua_config_get_ndim_pm_nc_factor(LuaConfig * lc);
            int * lua_config_get_shape_pm_nc_factor(LuaConfig * lc);
            int lua_config_has_lpt_nc_factor(LuaConfig * lc);
            double lua_config_get_lpt_nc_factor(LuaConfig * lc);
            int lua_config_has_np_alloc_factor(LuaConfig * lc);
            double lua_config_get_np_alloc_factor(LuaConfig * lc);
            int lua_config_has_compute_potential(LuaConfig * lc);
            int lua_config_get_compute_potential(LuaConfig * lc);
            int lua_config_has_n_shell(LuaConfig * lc);
            double lua_config_get_n_shell(LuaConfig * lc);
            int lua_config_has_lvk(LuaConfig * lc);
            int lua_config_get_lvk(LuaConfig * lc);
            int lua_config_has_n_side(LuaConfig * lc);
            double lua_config_get_n_side(LuaConfig * lc);
            int lua_config_has_every_ncdm(LuaConfig * lc);
            double lua_config_get_every_ncdm(LuaConfig * lc);
            int lua_config_has_ncdm_sphere_scheme(LuaConfig * lc);
            int lua_config_get_ncdm_sphere_scheme(LuaConfig * lc);
            int lua_config_has_ncdm_matterlike(LuaConfig * lc);
            int lua_config_get_ncdm_matterlike(LuaConfig * lc);
            int lua_config_has_ncdm_freestreaming(LuaConfig * lc);
            int lua_config_get_ncdm_freestreaming(LuaConfig * lc);
            int lua_config_has_growth_mode(LuaConfig * lc);
            int lua_config_get_growth_mode(LuaConfig * lc);
            int lua_config_has_painter_type(LuaConfig * lc);
            int lua_config_get_painter_type(LuaConfig * lc);
            int lua_config_has_painter_support(LuaConfig * lc);
            int lua_config_get_painter_support(LuaConfig * lc);
            int lua_config_has_force_mode(LuaConfig * lc);
            int lua_config_get_force_mode(LuaConfig * lc);
            int lua_config_has_enforce_broadband_kmax(LuaConfig * lc);
            int lua_config_get_enforce_broadband_kmax(LuaConfig * lc);
            int lua_config_has_f_nl_type(LuaConfig * lc);
            int lua_config_get_f_nl_type(LuaConfig * lc);
            int lua_config_has_f_nl(LuaConfig * lc);
            double lua_config_get_f_nl(LuaConfig * lc);
            int lua_config_has_kmax_primordial_over_knyquist(LuaConfig * lc);
            double lua_config_get_kmax_primordial_over_knyquist(LuaConfig * lc);
            int lua_config_has_scalar_amp(LuaConfig * lc);
            double lua_config_get_scalar_amp(LuaConfig * lc);
            int lua_config_has_scalar_pivot(LuaConfig * lc);
            double lua_config_get_scalar_pivot(LuaConfig * lc);
            int lua_config_has_scalar_spectral_index(LuaConfig * lc);
            double lua_config_get_scalar_spectral_index(LuaConfig * lc);
            int lua_config_has_read_lineark(LuaConfig * lc);
            const char * lua_config_get_read_lineark(LuaConfig * lc);
            int lua_config_has_read_powerspectrum(LuaConfig * lc);
            const char * lua_config_get_read_powerspectrum(LuaConfig * lc);
            int lua_config_has_read_linear_growth_rate(LuaConfig * lc);
            const char * lua_config_get_read_linear_growth_rate(LuaConfig * lc);
            int lua_config_has_linear_density_redshift(LuaConfig * lc);
            double lua_config_get_linear_density_redshift(LuaConfig * lc);
            int lua_config_has_read_lineark_ncdm(LuaConfig * lc);
            const char * lua_config_get_read_lineark_ncdm(LuaConfig * lc);
            int lua_config_has_read_powerspectrum_ncdm(LuaConfig * lc);
            const char * lua_config_get_read_powerspectrum_ncdm(LuaConfig * lc);
            int lua_config_has_read_linear_growth_rate_ncdm(LuaConfig * lc);
            const char * lua_config_get_read_linear_growth_rate_ncdm(LuaConfig * lc);
            int lua_config_has_linear_density_redshift_ncdm(LuaConfig * lc);
            double lua_config_get_linear_density_redshift_ncdm(LuaConfig * lc);
            int lua_config_has_read_grafic(LuaConfig * lc);
            const char * lua_config_get_read_grafic(LuaConfig * lc);
            int lua_config_has_read_runpbic(LuaConfig * lc);
            const char * lua_config_get_read_runpbic(LuaConfig * lc);
            int lua_config_has_read_whitenoisek(LuaConfig * lc);
            const char * lua_config_get_read_whitenoisek(LuaConfig * lc);
            int lua_config_has_sigma8(LuaConfig * lc);
            double lua_config_get_sigma8(LuaConfig * lc);
            int lua_config_has_random_seed(LuaConfig * lc);
            int lua_config_get_random_seed(LuaConfig * lc);
            int lua_config_has_shift(LuaConfig * lc);
            int lua_config_get_shift(LuaConfig * lc);
            int lua_config_has_inverted_ic(LuaConfig * lc);
            int lua_config_get_inverted_ic(LuaConfig * lc);
            int lua_config_has_remove_cosmic_variance(LuaConfig * lc);
            int lua_config_get_remove_cosmic_variance(LuaConfig * lc);
            int lua_config_has_write_lineark(LuaConfig * lc);
            const char * lua_config_get_write_lineark(LuaConfig * lc);
            int lua_config_has_write_whitenoisek(LuaConfig * lc);
            const char * lua_config_get_write_whitenoisek(LuaConfig * lc);
            int lua_config_has_write_runpbic(LuaConfig * lc);
            const char * lua_config_get_write_runpbic(LuaConfig * lc);
            int lua_config_has_write_powerspectrum(LuaConfig * lc);
            const char * lua_config_get_write_powerspectrum(LuaConfig * lc);
            int lua_config_has_write_snapshot(LuaConfig * lc);
            const char * lua_config_get_write_snapshot(LuaConfig * lc);
            int lua_config_has_write_nonlineark(LuaConfig * lc);
            const char * lua_config_get_write_nonlineark(LuaConfig * lc);
            int lua_config_has_write_runpb_snapshot(LuaConfig * lc);
            const char * lua_config_get_write_runpb_snapshot(LuaConfig * lc);
            int lua_config_has_particle_fraction(LuaConfig * lc);
            double lua_config_get_particle_fraction(LuaConfig * lc);
            int lua_config_has_sort_snapshot(LuaConfig * lc);
            int lua_config_get_sort_snapshot(LuaConfig * lc);
            int lua_config_has_write_fof(LuaConfig * lc);
            const char * lua_config_get_write_fof(LuaConfig * lc);
            int lua_config_has_fof_linkinglength(LuaConfig * lc);
            double lua_config_get_fof_linkinglength(LuaConfig * lc);
            int lua_config_has_fof_nmin(LuaConfig * lc);
            double lua_config_get_fof_nmin(LuaConfig * lc);
            int lua_config_has_fof_kdtree_thresh(LuaConfig * lc);
            double lua_config_get_fof_kdtree_thresh(LuaConfig * lc);
            int lua_config_has_write_rfof(LuaConfig * lc);
            const char * lua_config_get_write_rfof(LuaConfig * lc);
            int lua_config_has_rfof_kdtree_thresh(LuaConfig * lc);
            double lua_config_get_rfof_kdtree_thresh(LuaConfig * lc);
            int lua_config_has_rfof_linkinglength(LuaConfig * lc);
            double lua_config_get_rfof_linkinglength(LuaConfig * lc);
            int lua_config_has_rfof_nmin(LuaConfig * lc);
            double lua_config_get_rfof_nmin(LuaConfig * lc);
            int lua_config_has_rfof_l1(LuaConfig * lc);
            double lua_config_get_rfof_l1(LuaConfig * lc);
            int lua_config_has_rfof_l6(LuaConfig * lc);
            double lua_config_get_rfof_l6(LuaConfig * lc);
            int lua_config_has_rfof_a1(LuaConfig * lc);
            double lua_config_get_rfof_a1(LuaConfig * lc);
            int lua_config_has_rfof_a2(LuaConfig * lc);
            double lua_config_get_rfof_a2(LuaConfig * lc);
            int lua_config_has_rfof_b1(LuaConfig * lc);
            double lua_config_get_rfof_b1(LuaConfig * lc);
            int lua_config_has_rfof_b2(LuaConfig * lc);
            double lua_config_get_rfof_b2(LuaConfig * lc);
            int lua_config_has_lc_amin(LuaConfig * lc);
            double lua_config_get_lc_amin(LuaConfig * lc);
            int lua_config_has_lc_amax(LuaConfig * lc);
            double lua_config_get_lc_amax(LuaConfig * lc);
            int lua_config_has_lc_write_usmesh(LuaConfig * lc);
            const char * lua_config_get_lc_write_usmesh(LuaConfig * lc);
            int lua_config_has_lc_usmesh_alloc_factor(LuaConfig * lc);
            double lua_config_get_lc_usmesh_alloc_factor(LuaConfig * lc);
            int lua_config_has_lc_usmesh_fof_padding(LuaConfig * lc);
            double lua_config_get_lc_usmesh_fof_padding(LuaConfig * lc);
            int lua_config_has_lc_usmesh_ell_limit(LuaConfig * lc);
            double lua_config_get_lc_usmesh_ell_limit(LuaConfig * lc);
            int lua_config_has_lc_usmesh_tiles(LuaConfig * lc);
            double * lua_config_get_lc_usmesh_tiles_full(LuaConfig * lc, int * size);
            double * lua_config_get_lc_usmesh_tiles(LuaConfig * lc);
            int lua_config_get_n_lc_usmesh_tiles(LuaConfig * lc);
            int lua_config_get_ndim_lc_usmesh_tiles(LuaConfig * lc);
            int * lua_config_get_shape_lc_usmesh_tiles(LuaConfig * lc);
            int lua_config_has_dh_factor(LuaConfig * lc);
            double lua_config_get_dh_factor(LuaConfig * lc);
            int lua_config_has_lc_fov(LuaConfig * lc);
            double lua_config_get_lc_fov(LuaConfig * lc);
            int lua_config_has_lc_octants(LuaConfig * lc);
            double * lua_config_get_lc_octants_full(LuaConfig * lc, int * size);
            double * lua_config_get_lc_octants(LuaConfig * lc);
            int lua_config_get_n_lc_octants(LuaConfig * lc);
            int lua_config_get_ndim_lc_octants(LuaConfig * lc);
            int * lua_config_get_shape_lc_octants(LuaConfig * lc);
            int lua_config_has_lc_glmatrix(LuaConfig * lc);
            double * lua_config_get_lc_glmatrix_full(LuaConfig * lc, int * size);
            double * lua_config_get_lc_glmatrix(LuaConfig * lc);
            int lua_config_get_n_lc_glmatrix(LuaConfig * lc);
            int lua_config_get_ndim_lc_glmatrix(LuaConfig * lc);
            int * lua_config_get_shape_lc_glmatrix(LuaConfig * lc);
            int lua_config_has_za(LuaConfig * lc);
            int lua_config_get_za(LuaConfig * lc);
            int lua_config_has_kernel_type(LuaConfig * lc);
            int lua_config_get_kernel_type(LuaConfig * lc);
            int lua_config_has_force_softening_type(LuaConfig * lc);
            int lua_config_get_force_softening_type(LuaConfig * lc);
            int lua_config_has_constraints(LuaConfig * lc);
            double * lua_config_get_constraints_full(LuaConfig * lc, int * size);
            double * lua_config_get_constraints(LuaConfig * lc);
            int lua_config_get_n_constraints(LuaConfig * lc);
            int lua_config_get_ndim_constraints(LuaConfig * lc);
            int * lua_config_get_shape_constraints(LuaConfig * lc);
            int lua_config_has_set_mode_method(LuaConfig * lc);
            const char * lua_config_get_set_mode_method(LuaConfig * lc);
            int lua_config_has_set_mode(LuaConfig * lc);
            double * lua_config_get_set_mode_full(LuaConfig * lc, int * size);
            double * lua_config_get_set_mode(LuaConfig * lc);
            int lua_config_get_n_set_mode(LuaConfig * lc);
            int lua_config_get_ndim_set_mode(LuaConfig * lc);
            int * lua_config_get_shape_set_mode(LuaConfig * lc);
            int lua_config_has_pgdc(LuaConfig * lc);
            int lua_config_get_pgdc(LuaConfig * lc);
            int lua_config_has_pgdc_alpha0(LuaConfig * lc);
            double lua_config_get_pgdc_alpha0(LuaConfig * lc);
            int lua_config_has_pgdc_A(LuaConfig * lc);
            double lua_config_get_pgdc_A(LuaConfig * lc);
            int lua_config_has_pgdc_B(LuaConfig * lc);
            double lua_config_get_pgdc_B(LuaConfig * lc);
            int lua_config_has_pgdc_kl(LuaConfig * lc);
            double lua_config_get_pgdc_kl(LuaConfig * lc);
            int lua_config_has_pgdc_ks(LuaConfig * lc);
            double lua_config_get_pgdc_ks(LuaConfig * lc);
